version: '3.8'

services:

  # Backend API
  smart-brain-api:
    container_name: backend
    # image: node:16.0.0
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_USER: chansoo
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    # deleted 'links' has replaced by networks  
    # links:
    #   - postgres
    #   - redis
    ports:
      - "80:80"
    volumes:
      - ./:/usr/src/smart-brain-api

  # Postgres
  postgres:
    environment:
      POSTGRES_USER: chansoo
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"
