# The version sould be 3.3 since it's compatible with Redis
version: '3.3'

services:

  # Backend API
  smart-brain-api:
    container_name: backend
    # image: node:16.0.0
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_USER: chansoo
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "80:80"
    volumes:
      - ./:/usr/src/smart-brain-api

  # Postgres
  postgres:
    environment:
      POSTGRES_USER: chansoo
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
