version: '3.8'

services:

  # Backend API
  smart-brain-api:
    container_name: backend
    # image: node:16.0.0
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "80:80"
    volumes:
      - ./:/usr/src/smart-brain-api

  # Postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"

